Bold Conference Webste-Capstone Project
roodjinocherilus/Bold-Conference-Capstone pull request #1
Opened 2022-11-26 17:27 UTC by roodjinocherilus

Website of Bold Conference as my Capstone Project

2022-11-26 19:32 UTC, TuyishimireEric reviewed
# Status: INVALID PULL REQUEST
## Hi @roodjinocherilus  :hand: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
Invalid Code Review Request

### Your project is Invalid :no_entry: 
- [ ] You have to use updated Microverse readme
    - Kindly use the updated version of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme, this is a requirement to get a review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray

### Cheers and Happy coding! :clap: :clap: :clap:

---

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @TuyishimireEric_

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

2022-11-26 22:13 UTC, zieeco requested changes
Hi @roodjinocherilus ,


Great job so far! 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
_Check the comments under the review._

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-26 22:13 UTC, zieeco commented on README.md
> +
- Please, let's give appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/) to make our readme more professional.

2022-11-26 22:43 UTC, roodjinocherilus commented on README.md
> +
Hello @zieeco! Thank you for your feedback!

I agree the project needs some improvement in the design, and We must try to follow the design guideline, but they have also said we can personalize the content. here are the exact words: _**" We provide some design guidelines for you to create the website, but you must personalize the content, i.e., instead of a conference you can build a website for a concert or for a web development course. It's very important that you personalize your project so that you have something unique in your portfolio to share with potential employers during job searching. "**

"The something unique in the portfolio..." part is really important and that is the main reason we need to personalize it if possible. And if we personalize, the structure can still be the same, but some design guidelines will change, and color and assets will change according to the brand you are working for.

So it makes sense why the design is not perfectly the same as the one Microverse Provided.

2022-11-27 00:47 UTC, fherrerao commented on index.html
> +    </section>
- [ ] Kindly, as @zieeco mentioned [here](https://github.com/roodjinocherilus/Bold-Conference-Capstone/pull/1#discussion_r1032832836) 🎲, the hamburger menu should be at the left of the page. Please, relocate it. Remember to check always the original design and follow it, in this way you will improve your skills and attention to detail. 🐎
- [ ] Please, the colors, the font family (Cocogoose), and page layout, background color. The background should be transparent to match the design. 🥇

![image](https://user-images.githubusercontent.com/91301423/204113546-559eed74-216d-49b3-82bd-6330bf9aab64.png)

2022-11-27 00:47 UTC, fherrerao commented on index.html
> +      </section>
- [ ] Kindly, as requested by the previous reviewer [here](https://github.com/roodjinocherilus/Bold-Conference-Capstone/pull/1#discussion_r1032833817) ⚡, please update your design to stick with the original, take care with the alignment and the position of the elements 💯.

Your design:

![image](https://user-images.githubusercontent.com/91301423/204113816-544d8460-0c31-4741-92b4-dda46ce27b8a.png)

Original design:

![image](https://user-images.githubusercontent.com/91301423/204113825-51afb6de-1214-4dbc-a94d-b1944c0de5f5.png)

2022-11-27 00:47 UTC, fherrerao commented on index.html
> +      </section>
- [ ] I know that your project looks really well 💯, but remember in the requirements says that you should stick as much as possible with the original design. Please, try to follow the design provided by Microverse in this section:

Your design:

![image](https://user-images.githubusercontent.com/91301423/204113909-c7bbe4f8-6409-4f5f-84f9-2b31b2b28bf5.png)

Original design:

![image](https://user-images.githubusercontent.com/91301423/204113916-7089b0a1-a873-49ff-ac9d-b17b3c780a17.png)

2022-11-27 00:47 UTC, fherrerao commented on index.html
> +      </section>
- [ ] Kindly, the same as the [previous](https://github.com/roodjinocherilus/Bold-Conference-Capstone/pull/1#discussion_r1032835319) reviews, you should stick to the original design 🎲. Please use de correct background color and styles in this section.

Your design:

![image](https://user-images.githubusercontent.com/91301423/204114037-5405be1f-25ba-4bf5-95bc-65bce090765b.png)

Original design:

![image](https://user-images.githubusercontent.com/91301423/204114043-f6edfac9-7b28-4177-a327-c88913c7a6b5.png)

2022-11-27 00:47 UTC, fherrerao commented on README.md
> +
Hi @roodjinocherilus, as you say in the guideline say that you must personalize your project, but just in the content or the topic of the project and not in the fonts, styles, position, and space between the elements, you can check again here part of the requirements:

![image](https://user-images.githubusercontent.com/91301423/204114225-4f06a293-2d8a-48a0-881b-52bd6ce907d2.png)

Part of the goal for this project is to share your capabilities to create a website that sticks as much as possible to a given design. 🏯

2022-11-27 00:47 UTC, fherrerao requested changes
# 🦺 🚧 🚥 CHANGES REQUIRED 🚥 🚧 🦺
#
Hi @roodjinocherilus 💯, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![So Close Snl GIF by Saturday Night Live](https://user-images.githubusercontent.com/91301423/197784121-950974af-5415-4bf0-871b-ce226a51ace4.gif)
 ## Highlights

✔️  No linter errors.
✔️  You used the correct GitHub-Flow.
✔️  Good README
✔️  Good Commit Messages

 ## Required Changes ♻️
- [ ] Good job creating this capstone project, I know that your design looks awesome 🥇, but part of the goal for this project is to share your capabilities to create a website that sticks as much as possible to a given design 🎲 . For that reason please, should update your project with the changes requested by @zieeco. ⚡

- [ ] _Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-27 04:00 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi @roodjinocherilus 🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Great job implementing the featured section dynamically ✅
- Your project is professional ✅
- Good Video presentation ✅
- Your repo is professional ✅
- Well structured files ✅
- No Linter errors ✅
- Professional README.md file 💯


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


## Optional suggestions

- Check my comments below ⬇

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-27 04:10 UTC, merged